export default {
  KaohsiungCity: '高雄市',
  PingtungCountry: '屏東縣',
  TainanCity: '臺南市',
  HsinchuCity: '新竹市',
  HsinchuCountry: '新竹縣',
  YilanCountry: '宜蘭縣',
  KeelungCity: '基隆市',
  MiaoliCountry: '苗栗縣',
  TaipeiCity: '臺北市',
  NewTaipeiCity: '新北市',
  TaoyuanCountry: '桃園市',
  ChanghuaCountry: '彰化縣',
  ChiayiCountry: '嘉義縣',
  ChiayiCity: '嘉義市',
  HualienCountry: '花蓮縣',
  NantouCountry: '南投縣',
  TaichungCity: '臺中市',
  YunlinCountry: '雲林縣',
  TaitungCountry: '臺東縣',
  PenghuCountry: '澎湖縣',
  KinmenCountry: '金門縣',
  LienchiangCountry: '連江縣',
} as const;